encurtador/short/urls.py
from django.conf.urls import url
from django.contrib import admin


from . import views


app_name = 'short'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    #shorts/<url_id>/
    url(r'^(?P<url_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_url/$', views.create_url, name='create_url'),
    url(r'^(?P<urlcurta>[\W-]+){6,15}/$', views.UrlCBView.as_view, name='urlcurta' ),

    url(r'^nova/$', views.UrlView.as_view(), name='nova'),
]

encurtador/urls/short/urls.py
from django.conf.urls import url
from django.contrib import admin


from . import views


app_name = 'short'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    #shorts/<url_id>/
    url(r'^(?P<url_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_url/$', views.create_url, name='create_url'),
    url(r'^(?P<urlcurta>[\W-]+){6,15}/$', views.UrlCBView.as_view, name='urlcurta' ),

    url(r'^nova/$', views.UrlView.as_view(), name='nova'),
]

encurtador/urls/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from short.views import redirect_root

urlpatterns = [
    url(r'^$', redirect_root),
    url(r'^short/', include('short.urls')),
    url(r'^admin/', admin.site.urls),


]

encurtador/urls/urls/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from short.views import redirect_root

urlpatterns = [
    url(r'^$', redirect_root),
    url(r'^short/', include('short.urls')),
    url(r'^admin/', admin.site.urls),


]

encurtador/short/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
from django.conf import settings
from .validators import validade_url, validate_com
from .utils import code_generetor, create_shortcode


SHORTCODE_MAX = getattr(settings, "SHORTCODE_MAX", 15)

class UrlManager(models.Manager):
    def all(self, *args, **kwargs):
        qs_main = super(UrlManager, self).all(*args, **kwargs)
        qs = qs_main.filter(active=True)
        return qs


    def refresh_shortcodes(self, new_code=None):
        qs = Urls.objects.filter(id__gte=1)
        new_code = 0
        for q in qs:
            q.urlcurta = create_shortcode(q)
            print(q.urlcurta)
            q.save()
            new_code += 1
        return "New Codes: {i}".format(i=new_code)

class Urls(models.Model):
    titulo_url = models.CharField(max_length=100, null=True, blank=True)
    urlnormal = models.CharField(max_length=10000, unique=False, validators=[validade_url,  validate_com])
    urlcurta = models.CharField(max_length=SHORTCODE_MAX, unique=True, blank=True)
    user = models.ForeignKey(User, default=0,  null=True)

    objects = UrlManager()

    def save(self, *args, **kwargs):
        if self.urlcurta is None or self.urlcurta == "":
            self.urlcurta = create_shortcode(self)
        super(Urls, self).save(*args, **kwargs)

    def __str__(self):
        return self.urlnormal

encurtador/urls/short/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
from django.conf import settings
from .validators import validade_url, validate_com
from .utils import code_generetor, create_shortcode


SHORTCODE_MAX = getattr(settings, "SHORTCODE_MAX", 15)

class UrlManager(models.Manager):
    def all(self, *args, **kwargs):
        qs_main = super(UrlManager, self).all(*args, **kwargs)
        qs = qs_main.filter(active=True)
        return qs


    def refresh_shortcodes(self, new_code=None):
        qs = Urls.objects.filter(id__gte=1)
        new_code = 0
        for q in qs:
            q.urlcurta = create_shortcode(q)
            print(q.urlcurta)
            q.save()
            new_code += 1
        return "New Codes: {i}".format(i=new_code)

class Urls(models.Model):
    titulo_url = models.CharField(max_length=100, null=True, blank=True)
    urlnormal = models.CharField(max_length=10000, unique=False, validators=[validade_url,  validate_com])
    urlcurta = models.CharField(max_length=SHORTCODE_MAX, unique=True, blank=True)
    user = models.ForeignKey(User, default=0,  null=True)

    objects = UrlManager()

    def save(self, *args, **kwargs):
        if self.urlcurta is None or self.urlcurta == "":
            self.urlcurta = create_shortcode(self)
        super(Urls, self).save(*args, **kwargs)

    def __str__(self):
        return self.urlnormal

encurtador/short/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Urls
from .validators import validade_url, validate_com



class FormularioURL(forms.Form):
    titulo_url = forms.CharField(label='Título URL')
    urlnormal = forms.CharField(label='Encurtar URL', validators=[validade_url, validate_com])

    '''def clean(self):
        cleaned_data = super(FormularioURL, self). clean()
        print(cleaned_data)
        url = cleaned_data.get('urlnormal')
        url_validator = URLValidator()
        try:
            url_validator(url)
        except:
            raise forms.ValidationError("URL Inválida")
        print(url)
    
    def clean_url(self):
        url = self.cleaned_data['urlnormal']
        #print(url)

        url_validator = URLValidator()
        try:
            url_validator(url)
        except:
            raise forms.ValidationError("URL inválida")
        return url
    '''

class UrlsForm(forms.ModelForm):

    class Meta:
        model = Urls
        fields = ['titulo_url', 'urlnormal', 'urlcurta']

    def clean(self):
        cleaned_data = super(UrlsForm, self). clean()
        print(cleaned_data)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

encurtador/urls/short/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Urls
from .validators import validade_url, validate_com



class FormularioURL(forms.Form):
    titulo_url = forms.CharField(label='Título URL')
    urlnormal = forms.CharField(label='Encurtar URL', validators=[validade_url, validate_com])

    '''def clean(self):
        cleaned_data = super(FormularioURL, self). clean()
        print(cleaned_data)
        url = cleaned_data.get('urlnormal')
        url_validator = URLValidator()
        try:
            url_validator(url)
        except:
            raise forms.ValidationError("URL Inválida")
        print(url)
    
    def clean_url(self):
        url = self.cleaned_data['urlnormal']
        #print(url)

        url_validator = URLValidator()
        try:
            url_validator(url)
        except:
            raise forms.ValidationError("URL inválida")
        return url
    '''

class UrlsForm(forms.ModelForm):

    class Meta:
        model = Urls
        fields = ['titulo_url', 'urlnormal', 'urlcurta']

    def clean(self):
        cleaned_data = super(UrlsForm, self). clean()
        print(cleaned_data)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

encurtador/short/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import context
from django.contrib.sessions.models import Session
from .models import Urls
from .forms import UrlsForm, UserForm, FormularioURL
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View


# Create your views here.
def index(request):
    if not request.user.is_authenticated():
        return render(request, 'short/home.html')
    else:
        urls = Urls.objects.filter(user=request.user)
        return render(request, 'short/index.html', {'urls': urls})


def detail(request, url_id):
    url = get_object_or_404(Urls, pk=url_id)
    return render(request, 'short/detail.html', {'url': url})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                urls = Urls.objects.filter(user=request.user)
                return render(request, 'short/index.html', {'urls': urls})
            else:
                return render(request, 'short/login.html', {'error_message': 'Sua conta não está ativa.'})
        else:
            return render(request, 'short/login.html', {'error_message': 'Login inválido ou inexistente'})
    return render(request, 'short/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                urls = Urls.objects.filter(user=request.user)
                return render(request, 'short/index.html', {'urls': urls})
    context = {
        "form": form,
    }
    return render(request, 'short/register.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'short/login.html', context)


def create_url(request):

        form = UrlsForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            url = form.save(commit=False)
            url.user = request.user
            return UrlsForm(request, 'short/detail.html', {'url': url})
        context = {
            "form": form,
        }
        return render(request, 'short/create_url.html', context)

def delete_url(request, url_id):
    url = Urls.objects.get(pk=url_id)
    url.delete()
    urls = Urls.objects.filter(user=request.user)
    return render(request, 'short/index.html', {'urls': urls})


def url_redirect_view(request, urlcurta=None, *args, **kwargs):
    obj = get_object_or_404(request, urlcurta=None)
    return HttpResponse("URL: {sc}".format(sc=obj.urlnormal))


def url_view_fbv(request, *args, **kwargs):
    if request.method == "POST":
        print(request.POST)
    return render(request, "short/nova_url.html", {})

class UrlView(View):
    def get(self, request, *args, **kwargs):
        form = FormularioURL()
        context = {
            "title" : "Encurtar URL",
            "form" : form
        }
        return render(request, 'short/nova_url.html', context)

    def post(self, request, *args, **kwargs):

        form = FormularioURL(request.POST)
        context = {
            "title": "Encurtar URL",
            "form": form
        }

        template = "short/nova_url.html"

        if form.is_valid():
            user = request.user
            titulo_url = form.cleaned_data['titulo_url']
            new_url = form.cleaned_data['urlnormal']
            obj, created = Urls.objects.get_or_create(urlnormal=new_url, titulo_url=titulo_url)
            context = {
                "object": obj,
                "created": created,
            }

            if created:
                template = "short/sucesso.html"
            else:
                template = "short/existe.html"


        return render(request, template , context)

class UrlCBView(View):
    def get(self, request, urlcurta=None, *args, **kwargs):
        obj = get_object_or_404(Urls, urlcurta=urlcurta)
        return HttpResponseRedirect(obj.urlnormal)

def redirect_root(request):
    return redirect('/short/')

encurtador/urls/short/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import context
from django.contrib.sessions.models import Session
from .models import Urls
from .forms import UrlsForm, UserForm, FormularioURL
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View


# Create your views here.
def index(request):
    if not request.user.is_authenticated():
        return render(request, 'short/home.html')
    else:
        urls = Urls.objects.filter(user=request.user)
        return render(request, 'short/index.html', {'urls': urls})


def detail(request, url_id):
    url = get_object_or_404(Urls, pk=url_id)
    return render(request, 'short/detail.html', {'url': url})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                urls = Urls.objects.filter(user=request.user)
                return render(request, 'short/index.html', {'urls': urls})
            else:
                return render(request, 'short/login.html', {'error_message': 'Sua conta não está ativa.'})
        else:
            return render(request, 'short/login.html', {'error_message': 'Login inválido ou inexistente'})
    return render(request, 'short/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                urls = Urls.objects.filter(user=request.user)
                return render(request, 'short/index.html', {'urls': urls})
    context = {
        "form": form,
    }
    return render(request, 'short/register.html', context)


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'short/login.html', context)


def create_url(request):

        form = UrlsForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            url = form.save(commit=False)
            url.user = request.user
            return UrlsForm(request, 'short/detail.html', {'url': url})
        context = {
            "form": form,
        }
        return render(request, 'short/create_url.html', context)

def delete_url(request, url_id):
    url = Urls.objects.get(pk=url_id)
    url.delete()
    urls = Urls.objects.filter(user=request.user)
    return render(request, 'short/index.html', {'urls': urls})


def url_redirect_view(request, urlcurta=None, *args, **kwargs):
    obj = get_object_or_404(request, urlcurta=None)
    return HttpResponse("URL: {sc}".format(sc=obj.urlnormal))


def url_view_fbv(request, *args, **kwargs):
    if request.method == "POST":
        print(request.POST)
    return render(request, "short/nova_url.html", {})

class UrlView(View):
    def get(self, request, *args, **kwargs):
        form = FormularioURL()
        context = {
            "title" : "Encurtar URL",
            "form" : form
        }
        return render(request, 'short/nova_url.html', context)

    def post(self, request, *args, **kwargs):

        form = FormularioURL(request.POST)
        context = {
            "title": "Encurtar URL",
            "form": form
        }

        template = "short/nova_url.html"

        if form.is_valid():
            user = request.user
            titulo_url = form.cleaned_data['titulo_url']
            new_url = form.cleaned_data['urlnormal']
            obj, created = Urls.objects.get_or_create(urlnormal=new_url, titulo_url=titulo_url)
            context = {
                "object": obj,
                "created": created,
            }

            if created:
                template = "short/sucesso.html"
            else:
                template = "short/existe.html"


        return render(request, template , context)

class UrlCBView(View):
    def get(self, request, urlcurta=None, *args, **kwargs):
        obj = get_object_or_404(Urls, urlcurta=urlcurta)
        return HttpResponseRedirect(obj.urlnormal)

def redirect_root(request):
    return redirect('/short/')

encurtador/short/templates/short/base.html
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Url's {% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'short/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Logo -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">

                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>

                <a class="navbar-brand" href="{% url 'short:index' %}" >Encurtador</a>
            </div>


            <!-- Itens  -->
            <div class="collapse navbar-collapse" id="topNavBar">

                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'short:index' %}">
                            <span class="glyphicon glyphicon-anchor" aria-hidden="true"></span>&nbsp; Urls
                        </a>
                    </li>
                </ul>




                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'short:create_url' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Url
                        </a>
                    </li>

                    <li class="">
                        <a href="{% url 'short:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

encurtador/short/templates/short/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Urls{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'shot/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'short/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'short:index' %}">Encurtador</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'short:register' %}">Cadastrar</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'short:login_user' %}">Login</a></li>
                <li class="{% block nova_active %}{% endblock %}"><a href="{% url 'short:nova' %}">Encurtar uma URL</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

encurtador/short/templates/short/create_url.html
{% extends 'short/base.html' %}
{% block title %}Criar URL{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Criar URL</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'short/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Encurtar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">


                    <h3>Dúvidas?</h3>
                    <ul>
                        <li>Identifique o seu link, para que possa se lembrar sobre o que é.</li>
                        <li>E cole a URL que deseja encurtar</li>
                    </ul>
                </div>
            </div>
        </div>



    </div>

</div>
{% endblock %}

encurtador/short/templates/short/delete_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

encurtador/short/templates/short/detail.html
{% extends 'short/base.html' %}
{% block urls_active %}active{% endblock %}
{% block title %} Detalhes da URL {% endblock %}<
{% block body %}

    <h2> {{ url.titulo_url }}</h2>
    Url Curta: <a href="{{ url.urlnormal }}">{% url.urlcurta }</a><br />
    Url Normal: <a href="{{ url.urlnormal }}">{{ url.urlnormal }}</a>


{% endblock %}

encurtador/short/templates/short/existe.html
{% extends 'short/base_visitor.html' %}
{% block title %}URL já Existe{% endblock %}

{% block body %}
<h3>URL Já existente</h3>
<p>{{ object.titulo_url }}
<p>{{ object.urlnormal}}
<p>Short: <a href="{{ object.urlnormal }}">URL/{{ object.urlcurta }}</a>

    <br /><br />

    <a href="{% url 'short:nova' %}">Cadastrar uma nova URL</a>
{% endblock %}

encurtador/short/templates/short/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

encurtador/short/templates/short/home.html
{% extends 'short/base_visitor.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}




        <div class="col-sm-10 col-md-12">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'short:nova' %}">Encurtar uma URL</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Encurtador de Url's</h3:
                    <p>Economize caracteres nas redes sociais</p>


                </div>
            </div>

        </div>

{% endblock %}

encurtador/short/templates/short/index.html
{% extends 'short/base.html' %}
{% block albums_active %}active{% endblock %}

{% block body %}




        <div class="col-sm-10 col-md-12">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'short:nova' %}">Encurtar uma Nova URL</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Urls cadastradas</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Identificação</th>
                            <th>Url</th>
                            <th>Url-Curta</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for url in urls %}
                            <tr>
                                <td>{{ url.titulo_url }}</td>
                                <td>
                                    <a target="_blank" href="{{ urls.urlnormal }}">
                                        {{ url.urlnormal }}
                                    </a>
                                </td>
                                <td>
                                    <a target="_blank" href="{{ urls.urlnormal }}">
                                        {{ url.urlcurta }}
                                    </a>
                                    </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

{% endblock %}

encurtador/short/templates/short/login.html
{% extends 'short/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'short:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'short:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

encurtador/short/templates/short/register.html
{% extends 'short/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'short/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'short:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

encurtador/short/templates/short/sucesso.html
{% extends 'short/base_visitor.html' %}
{% block title %}URL criada{% endblock %}

{% block body %}
<h3>Url encurtada:</h3>
<p>ID: {{ object.titulo_url }}
<p>Url {{ object.urlnormal}}
<p>Short: <a href="{{ object.urlnormal }}">URL/{{ object.urlcurta }}</a>
    <br /><br />

    <a href="{% url 'short:nova' %}" class="btn">Cadastrar uma nova URL</a>
{% endblock %}